INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE) VALUES (100, 'teuzo@teste.com', '123456', 'ROLE_ADMIN');
INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE) VALUES (101, 'dalva@teste.com', '123456', 'ROLE_USER');
INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE) VALUES (102, 'lucas@teste.com', '123456', 'ROLE_USER');